# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BLVideoDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SDWebImage', '~> 5.0.0-beta3'
  pod 'SVProgressHUD'
  pod 'SnapKit', '~> 4.0.1'
  pod 'R.swift', '~> 5.0.0.alpha.2'
end
